// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaReuniao_WebAPI.Data;

namespace SalaReuniao_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SalaReuniao_WebAPI.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraFim")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Agendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = "06/06/2020",
                            HoraFim = "08:00",
                            HoraInicio = "07:00",
                            SalaId = 1,
                            Titulo = "Reuniao Mensal"
                        },
                        new
                        {
                            Id = 2,
                            Data = "23/06/2020",
                            HoraFim = "09:00",
                            HoraInicio = "08:00",
                            SalaId = 2,
                            Titulo = "Feedback"
                        },
                        new
                        {
                            Id = 3,
                            Data = "19/06/2020",
                            HoraFim = "10:00",
                            HoraInicio = "08:00",
                            SalaId = 3,
                            Titulo = "Dailyng"
                        },
                        new
                        {
                            Id = 4,
                            Data = "16/06/2020",
                            HoraFim = "11:00",
                            HoraInicio = "10:30",
                            SalaId = 4,
                            Titulo = "Sprint"
                        },
                        new
                        {
                            Id = 5,
                            Data = "01/07/2020",
                            HoraFim = "12:00",
                            HoraInicio = "11:00",
                            SalaId = 5,
                            Titulo = "Backlog"
                        });
                });

            modelBuilder.Entity("SalaReuniao_WebAPI.Models.Sala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacidade = 4,
                            descricao = "Sala Reuniao 1"
                        },
                        new
                        {
                            id = 2,
                            capacidade = 6,
                            descricao = "Sala Reuniao 2"
                        },
                        new
                        {
                            id = 3,
                            capacidade = 8,
                            descricao = "Sala Reuniao 3"
                        },
                        new
                        {
                            id = 4,
                            capacidade = 10,
                            descricao = "Sala Reuniao 4"
                        },
                        new
                        {
                            id = 5,
                            capacidade = 12,
                            descricao = "Sala Reuniao 5"
                        });
                });

            modelBuilder.Entity("SalaReuniao_WebAPI.Models.Agenda", b =>
                {
                    b.HasOne("SalaReuniao_WebAPI.Models.Sala", "Sala")
                        .WithMany("Agenda")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
